apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: wiz-webapp-backendconfig
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10      # THIS IS THE FIX (10 is less than 15)
    type: HTTP
    requestPath: / # Probing a path that actually exists
