apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: wiz-webapp-backendconfig
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    type: HTTP
    requestPath: /login # Tells the load balancer to check this valid path
