name: "3. Teardown Infrastructure"

on:
  workflow_dispatch: # This makes it a manual button in GitHub Actions

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terraform/
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
